/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.min;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Service;

@Service @ConfigurationProperties(prefix = "gradlegh.library") public class Library {
  private boolean someSetting = false;

  public boolean someLibraryMethod() {
    return true;
  }

  public boolean isSomeSetting() {
    return someSetting;
  }

  public void setSomeSetting(boolean someSetting) {
    this.someSetting = someSetting;
  }
}
